#!/bin/bash
#
# Output a one-liner info about
#   - wireless LAN
#   - display controller
#   - VGA compatible controller
# device.
# Finds the info from the output of 'lspci' command.

Usage() {
    test -n "$1" && echo "Error: $1." >&2

    cat <<EOF >&2
Usage: $0 option
where
   --wireless
   --wifi
   -w             shows info about the wireless LAN device

   --display
   -d             shows info about the display controller

   --vga
   -v             shows info about the VGA compatible controller
EOF
}

letters_of() {    # separate letters of $string with spaces
    local string="$1"
    echo "$string" | sed -e 's|\([a-z]\)|\1 |g' -e 's| $||'
}

Main()
{
    local search_this=""
    local arg xx letters

    test -n "$1" || { Usage "option missing" ; return 1 ; }

    for arg in "$@"
    do
        case "$arg" in
            -w | --wireless | --wifi | -wireless | -wifi)
                search_this=" Network controller: "
                ;;
            -d | --display | -display)
                search_this=" Display controller: "
                ;;
            -v | --vga | -vga)
                search_this=" VGA compatible controller: "
                ;;
            -w*|-d*|-v*)
                letters="$(letters_of "${arg:1}")"
                for xx in $letters ; do
                    case "$xx" in
                        w) Main -w ;;
                        d) Main -d ;;
                        v) Main -v ;;
                        *) Usage "unsupported option letter '$xx'" ; return 1 ;;
                    esac
                done
                continue
                ;;
            *)
                Usage "unsupported option '$arg'"
                return 1
                ;;
        esac
        lspci | grep "$search_this" | sed 's|^.*'"$search_this"'||'
    done
}

Main "$@"
