#!/bin/bash

# Fixes for current EOS installation.
# Run this with sudo.

Main() {
    local xx

    cd /etc/skel
    chown -R root:root .

    cd /usr/share/backgrounds/xfce
    for xx in blue stripes teal ; do
        rm -f xfce-$xx.{png,jpg}
        ln -s /usr/share/endeavouros/endeavouros-wallpaper.png xfce-$xx.jpg
    done
}

Main "$@"
