#!/bin/bash

# Install/remove a DE based on the package lists at
# https://github.com/endeavouros-team/EndeavourOS-packages-lists

# See: https://forum.endeavouros.com/t/how-often-should-you-reinstall-endeavour/19174/20

# Make it a GUI !!!

DIE() {
    echo "$progname: error: $1" >&2
    exit 1
}

KnownDEs() {
    ls -1 [a-z]* | grep -v eos-base-group
}

IsKnownDE() {
    local de="$1"
    local xx
    for xx in $(KnownDEs) ; do
        [ "$de" = "$xx" ] && return 0
    done
    return 1
}

Analyze() {
    local ii uu UP=()

    if [ -n "$uninstallDE" ] ; then
        UP=($(cat ${uninstallDE[*]}))
    fi

    installPkg=($(cat ${installDE[*]} eos-base-group))

    for uu in ${UP[*]} ; do
        for ii in ${installPkg[*]} ; do
            if [ "$uu" = "$ii" ] ; then
                continue 2
            fi
        done
        if pacman -Q "$uu" >& /dev/null ; then
            uninstallPkg+=("$uu")
        fi
    done
}

Do() {
    if [ "$dryrun" = "no" ] ; then
        "$@"
    else
        echo "$@"
    fi
}

Options() {
    local opts

    opts="$(/usr/bin/getopt -o=hi:u:n --longoptions help,install:,uninstall:,dryrun --name "$progname" -- "$@")" || {
        Options -h
        return 1
    }

    eval set -- "$opts"

    while true ; do
        case "$1" in
            -i | --install)
                IsKnownDE "$2" || DIE "sorry, $2 is not a known DE"
                installDE+=("$2")
                shift
                ;;
            -u | --uninstall)
                IsKnownDE "$2" || DIE "sorry, $2 is not a known DE"
                uninstallDE+=("$2")
                shift
                ;;
            -n | --dryrun)
                dryrun=yes
                ;;
            -h | --help)
                cat <<EOF >&2
Usage: $progname option
Options:
  -i, --install DE       Install the given DE.
  -u, --uninstall DE     Uninstall the given DE.
  -n, --dryrun           Show that would happen but change nothing.

Available DEs:
$(/usr/bin/ls -1 [a-z]*)
EOF
                ;;
            
            --) shift ; break ;;
        esac
        shift
    done
}

Install() {
    if [ -n "$installDE" ] ; then
        echo "===> Installing ${installDE[*]}"
        Do sudo pacman -S   --noconfirm --needed "${installPkg[@]}"
    fi
}

Uninstall() {
    if [ -n "$uninstallDE" ] ; then
        echo "===> Uninstalling ${uninstallDE[*]}"
        Do sudo pacman -Rsn --noconfirm "${uninstallPkg[@]}"
    fi
}

Main()
{
    local progname="$(/usr/bin/basename "$0")"
    local installDE=() installPkg=()
    local uninstallDE=() uninstallPkg=()
    local reponame=EndeavourOS-packages-lists
    local dryrun=no

    cd /tmp
    rm -rf $reponame
    git clone $(eos-github2gitlab https://github.com/endeavouros-team/$reponame.git) 2>/dev/null || return 1
    cd $reponame

    Options "$@"

    Analyze

    Uninstall
    Install
}

Main "$@"
