#!/bin/bash
#.
# EndeavourOS Xfce4 settings (experimental).
# These are additions to vanilla Xfce settings.

# mouse wheel behaviour
xfconf-query --channel xfwm4 --property /general/mousewheel_rollup --set false
xfconf-query --channel xfwm4 --property /general/scroll_workspaces --set false

# theme
xfconf-query --channel xsettings --property /Net/ThemeName     --set Arc-Dark
xfconf-query --channel xsettings --property /Net/IconThemeName --set Arc

# session
xfconf-query --channel xfce4-session --property /general/SaveOnExit --set false
