#!/bin/bash

Main() {
    local conf=/etc/eos-rankmirrors.conf
    source $conf || return

    local targets=$(cat)

    local timeout="$EOS_AUTORANK_TIMEOUT"
    [ -n "$timeout" ] || timeout=30

    /usr/bin/eos-rankmirrors --timeout $timeout --hook-rank $targets >/dev/null || true
    return 0
}

Main "$@"
