#!/bin/bash

source /usr/share/endeavouros/scripts/translations__common || exit 1

# The _LTR (associative) array below contains all English translations for this app.
# Each "entry" in _LTR consists of two elements: "key" and "translation-string".
# Technically, the "key" is used as the index to the associative array _LTR.
# Then _LTR[key] becomes a translation-string.

# The translation-string will be used as the format parameter to printf.
# So the translation-string may include one or more %s like placeholders for additional parameters.
#
# When writing a new translation it is easiest to copy the _LTR array entries from
# the English translation file (translations__en) to a new file
# (e.g. translations__de for German translations) and translate every "entry" in _LTR
# below this line.

declare -A _LTR=(
    cal_info2                     "<b>Offline</b> method gives you the %s desktop.\nInternet connection is not needed.\n\n"
    _commonphrase_not_found       "%s not found"
)
